GATEWAY_IP_ADDRESS=0.0.0.0
MAX_SIZE=10737418240
FILE_DIR=Files/
QUEUE_FILE=queue.dat
INDEX_FILE=_indexedItems.dat
URL_FILE=_urlList.dat
STATS_FILE=_stats.dat
SEARCHES_FILE=topSearches.dat
MAX_RETRIES=5
API_KEY=your-api-key-here



