GATEWAY_IP_ADDRESS=0.0.0.0
MAX_SIZE=10737418240
FILE_DIR=Files/
QUEUE_FILE=queue.dat
INDEX_FILE=_indexedItems.dat
URL_FILE=_urlList.dat
STATS_FILE=_stats.dat
SEARCHES_FILE=topSearches.dat
MAX_RETRIES=5
API_KEY=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



